{
	"version": 1716542923,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundhome-sheet0.png",
		"images/play-sheet0.png",
		"images/backgroundlevel1-sheet0.png",
		"images/huruf-sheet0.png",
		"images/huruf-sheet1.png",
		"images/huruf-sheet2.png",
		"images/huruf-sheet3.png",
		"images/huruf-sheet4.png",
		"images/huruf-sheet5.png",
		"images/huruf-sheet6.png",
		"images/huruf-sheet7.png",
		"images/tempatjawaban-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tempathuruf-sheet0.png",
		"images/buah-sheet0.png",
		"images/buah-sheet1.png",
		"images/particles.png",
		"images/goodjob-sheet0.png",
		"images/next-sheet0.png",
		"images/backroundend-sheet0.png",
		"images/home-sheet0.png",
		"media/gunshot-37055.ogg",
		"media/boing.ogg",
		"media/mouse click.ogg",
		"media/0513 (1).ogg",
		"media/tring sound effect.ogg",
		"media/y2meta.app-illit – magnetic _ instrumental-(128kbps).ogg",
		"media/y2meta.app-comedy background game by infraction [no copyright music] _ happy farm-(128kbps).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}